export const queryKeys = {
  getConsent: "getConsent",
  profiles: "profiles",
  ppp: "ppp",
  getNurseConsultationsForEachTenant: "getNurseConsultationsForEachTenant",
  markConsultationAsMissed: "arkConsultationAsMissed",
  markConsultationAsApproved: "markConsultationAsApproved",
  markConsultationAsRejected: "markConsultationAsRejected",
  getNurseConsulationDetailByOID: "getNurseConsulationDetailByOID",
  getPatientDetailByOID: "getPatientDetailByOID",
  getPatientByOID: "getPatientByOID",
  notes: "notes",
  note: "note",
  getPrescriberWithRespectToTenant: "getPrescriberWithRespectToTenant",
  getPrescriberWithRespectToTenantByConsulationPrescriberOid:
    "getPrescriberWithRespectToTenantByConsulationPrescriberOid",
  getPrescriberDetailsByPrescriberConsulationOID:
    "getPrescriberDetailsByPrescriberConsulationOID",
  getPrescriberConsulationDetailByOID: "getPrescriberConsulationDetailByOID",
  getNurseConsultations: "getNurseConsultations",
  prescriberProfilePatch: "prescriberProfilePatch",
  changePassword: "changePassword",
  getPrescriberProfileData: "getPrescriberProfileData",
  getSinglePatientDetail: "getSinglePatientDetail",
  products: "products",
  PRESCRIPTION: "PRESCRIPTION",
  getPrescriptionByOID: "getPrescriptionByOID",
  allPharmacy: "allPharmacy",
  postSentPrecriptionToPharmacy: "postSentPrecriptionToPharmacy",
  getPAperPrescriptions: "getPAperPrescriptions",
  patientConsultations: "patientConsultations",
  notifications: "notifications",
  createPrescription: "createPrescription",
  cancelledPrescriptions: "cancelledPrescriptions",
  unqualified: "unqualified",
  screeningQuestions: "screeningQuestions",
  unqualifiedPatients: "unqualifiedPatients",
  productOptions: "productOptions",
  ingredients: "ingredients",
  postIngredient: "postIngredient",
  postProduct: "postProduct",
  getPrescriptionsByPCOID: "getPrescriptionsByPCOID",
  debit: "debit",
  paid: "paid",
  getTPatientTimelineData: "getTPatientTimelineData",
  configurations: "configurations",
  allConsultationAdmin: "allConsultationAdmin",
};
